/* libadele_client_core — generated by cbindgen; do not edit by hand. */

#ifndef ADELE_CLIENT_CORE_H
#define ADELE_CLIENT_CORE_H

#pragma once

/* This file is auto-generated from the client-ui-ffi crate. Edit the Rust source and rebuild. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 The opaque handle the C side holds. Owns the tokio runtime (its drop shuts
 the worker threads + the actor down) and the channel into the actor.
 */
typedef struct Core Core;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Create a core instance. `callback` receives view-event JSON strings;
 `user_data` is passed back to it verbatim (carry your C++ `this` here).
 Returns an opaque handle, or null if `callback` is null. Free it with
 [`adele_core_free`].

 The callback type is spelled inline (rather than via the `ViewCallback`
 alias) so cbindgen emits a real nullable C function pointer rather than an
 opaque struct; `Option` is what lets Rust accept a null pointer safely.
 */
Core *adele_core_new(void (*callback)(void *user_data, const char *json), void *user_data);

/*
 Destroy a core instance, shutting down its runtime and connection.

 # Safety
 `core` must be a handle returned by [`adele_core_new`] (or null), and must
 not be used after this call.
 */
void adele_core_free(Core *core);

/*
 Connect to the daemon. `transport` is `"dbus"` (default for anything
 unrecognised), `"uds"`, or `"ws"`; `address` is the UDS socket path or WS url
 (empty for the default), ignored for D-Bus.

 # Safety
 `core` must be a live handle from [`adele_core_new`]; `transport`/`address`
 must be null or valid NUL-terminated C strings.
 */
void adele_core_connect(Core *core, const char *transport, const char *address);

/*
 Send a prompt into the open conversation.

 # Safety
 `core` must be a live handle; `text` must be null or a valid C string.
 */
void adele_core_send_prompt(Core *core, const char *text);

/*
 Open (load) a conversation by id.

 # Safety
 `core` must be a live handle; `conversation_id` must be null or a valid C string.
 */
void adele_core_select_conversation(Core *core, const char *conversation_id);

/*
 Create a new conversation and open it.

 # Safety
 `core` must be a live handle from [`adele_core_new`].
 */
void adele_core_new_conversation(Core *core);

/*
 Delete a conversation by id.

 # Safety
 `core` must be a live handle; `conversation_id` must be null or a valid C string.
 */
void adele_core_delete_conversation(Core *core, const char *conversation_id);

/*
 Set the `You:` (voice input) state for a conversation.

 # Safety
 `core` must be a live handle; `conversation_id` must be null or a valid C string.
 */
void adele_core_set_voice_in(Core *core, const char *conversation_id, bool enabled);

/*
 Set the `Adele:` (voice output) level for a conversation. `level` is
 `"disabled"`, `"on_demand"`, or `"always"` (anything else ⇒ `"disabled"`).

 # Safety
 `core` must be a live handle; `conversation_id`/`level` must be null or valid
 C strings.
 */
void adele_core_set_adele_output(Core *core, const char *conversation_id, const char *level);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ADELE_CLIENT_CORE_H */
