/* libadele_client_core — generated by cbindgen; do not edit by hand. */

#ifndef ADELE_CLIENT_CORE_H
#define ADELE_CLIENT_CORE_H

#pragma once

/* This file is auto-generated from the client-ui-ffi crate. Edit the Rust source and rebuild. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 The opaque handle the C side holds. Owns the tokio runtime (its drop shuts
 the worker threads + the actor down) and the channel into the actor.
 */
typedef struct Core Core;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Create a core instance. `callback` receives view-event JSON strings;
 `user_data` is passed back to it verbatim (carry your C++ `this` here).
 Returns an opaque handle, or null if `callback` is null. Free it with
 [`adele_core_free`].

 The callback type is spelled inline (rather than via the `ViewCallback`
 alias) so cbindgen emits a real nullable C function pointer rather than an
 opaque struct; `Option` is what lets Rust accept a null pointer safely.
 */
Core *adele_core_new(void (*callback)(void *user_data, const char *json), void *user_data);

/*
 Destroy a core instance, shutting down its runtime and connection.

 # Safety
 `core` must be a handle returned by [`adele_core_new`] (or null), and must
 not be used after this call.
 */
void adele_core_free(Core *core);

/*
 Connect to the daemon. `transport` is `"dbus"` (default for anything
 unrecognised), `"uds"`, or `"ws"`; `address` is the UDS socket path or WS url
 (empty for the default), ignored for D-Bus.

 # Safety
 `core` must be a live handle from [`adele_core_new`]; `transport`/`address`
 must be null or valid NUL-terminated C strings.
 */
void adele_core_connect(Core *core, const char *transport, const char *address);

/*
 Send a prompt into the open conversation.

 # Safety
 `core` must be a live handle; `text` must be null or a valid C string.
 */
void adele_core_send_prompt(Core *core, const char *text);

/*
 Check out queued message `index` into the composer to edit it (up-arrow
 recall / a chip's edit affordance). The text loads via a `composer_text` view
 event; re-submitting reinserts it in place. An out-of-range index is ignored.

 # Safety
 `core` must be a live handle from [`adele_core_new`].
 */
void adele_core_edit_queued(Core *core, uintptr_t index);

/*
 Remove queued message `index` (a chip's x) without sending it. An
 out-of-range index is ignored.

 # Safety
 `core` must be a live handle from [`adele_core_new`].
 */
void adele_core_remove_queued(Core *core, uintptr_t index);

/*
 Abandon an in-progress queued-message edit: the checked-out message returns
 to the queue unchanged and the composer clears. A no-op when not editing.

 # Safety
 `core` must be a live handle from [`adele_core_new`].
 */
void adele_core_cancel_queued_edit(Core *core);

/*
 Open (load) a conversation by id.

 # Safety
 `core` must be a live handle; `conversation_id` must be null or a valid C string.
 */
void adele_core_select_conversation(Core *core, const char *conversation_id);

/*
 Create a new conversation and open it.

 # Safety
 `core` must be a live handle from [`adele_core_new`].
 */
void adele_core_new_conversation(Core *core);

/*
 Delete a conversation by id.

 # Safety
 `core` must be a live handle; `conversation_id` must be null or a valid C string.
 */
void adele_core_delete_conversation(Core *core, const char *conversation_id);

/*
 Set the `You:` (voice input) state for a conversation.

 # Safety
 `core` must be a live handle; `conversation_id` must be null or a valid C string.
 */
void adele_core_set_voice_in(Core *core, const char *conversation_id, bool enabled);

/*
 Set the `Adele:` (voice output) level for a conversation. `level` is
 `"disabled"`, `"on_demand"`, or `"always"` (anything else ⇒ `"disabled"`).

 # Safety
 `core` must be a live handle; `conversation_id`/`level` must be null or valid
 C strings.
 */
void adele_core_set_adele_output(Core *core, const char *conversation_id, const char *level);

/*
 Stage (or clear) a per-message model override for the next send. Empty
 `connection_id`/`model_id` clears it (inherit the default); `effort` is
 `"low"`/`"medium"`/`"high"` or empty (no effort hint).

 # Safety
 `core` must be a live handle; the string args must be null or valid C strings.
 */
void adele_core_select_model(Core *core,
                             const char *connection_id,
                             const char *model_id,
                             const char *effort);

/*
 Request cancellation of a background task by id.

 # Safety
 `core` must be a live handle; `task_id` must be null or a valid C string.
 */
void adele_core_cancel_task(Core *core, const char *task_id);

/*
 Fetch a background task's log page; the result arrives later as a `task_logs`
 view event.

 # Safety
 `core` must be a live handle; `task_id` must be null or a valid C string.
 */
void adele_core_fetch_task_logs(Core *core, const char *task_id);

/*
 Stage an explicit WebSocket bearer token for the next [`adele_core_connect`]
 (empty ⇒ clear). Used verbatim as the WS bearer credential, bypassing the
 D-Bus / `/login` token minting — the path a client with no local token minter
 (e.g. macOS, which has no D-Bus bridge) uses after obtaining a token
 out-of-band from the daemon's `/login`. Ignored for non-WS transports.

 # Safety
 `core` must be a live handle; `jwt` must be null or a valid C string.
 */
void adele_core_set_ws_jwt(Core *core, const char *jwt);

/*
 Set whether basic device context (name, username, home dir, hostname,
 timezone, OS) is shared with the assistant on the next [`adele_core_connect`]
 (#549). `true` (the default) shares it so the assistant can personalize;
 `false` opts out, sending no context field / header at all. Staged on the
 core and applied when the next connect builds its `ConnectionConfig`, so a
 change takes effect on the following (re)connect. This backs the KDE KCM
 "Share device info with the assistant" checkbox.

 # Safety
 `core` must be a live handle from [`adele_core_new`].
 */
void adele_core_set_share_client_context(Core *core, bool enabled);

/*
 Declare which `client-mcp.toml` surface this client resolves its MCP servers
 (and `disabled_builtins`) under — `"mac"`, `"kde"`, … Server *definitions* are
 machine-wide; the surface is the per-client enable layer, so one set of
 servers can be configured once and switched on per client.

 Call this once before [`adele_core_connect`]; it is read when the connect
 starts the client MCP host, so a later change applies on the next
 (re)connect. A NULL or empty name is ignored and the core keeps its default
 surface (`kde`), which is what adele-kde relies on by never calling this.

 # Safety
 `core` must be a live handle from [`adele_core_new`]; `surface` must be NULL
 or a valid NUL-terminated UTF-8 string, borrowed for the call.
 */
void adele_core_set_mcp_surface(Core *core, const char *surface);

/*
 Ask for this client's compiled-in ("built-in") MCP servers and their status
 under the surface declared via [`adele_core_set_mcp_surface`]. The answer
 arrives as an `mcp_builtins` view event carrying, per server: `name`,
 `namespace`, `kind`, `tool_count`, `overridden_by` (the same-name external
 server shadowing it, or null), and `disabled_by_config` (this surface's
 opt-out).

 Answerable with **no connection**: which servers are built in is a property of
 how this cdylib was built (`--features mcp-*`) plus what `client-mcp.toml`
 says, so a settings panel can call this before the first connect. A core built
 with no `mcp-*` feature — adele-kde's — answers with an empty list, which is
 the honest "none linked in" rather than a missing reply.

 # Safety
 `core` must be a live handle from [`adele_core_new`].
 */
void adele_core_request_mcp_builtins(Core *core);

/*
 Ask for this client's external client-run MCP servers — the `client-mcp.toml`
 servers the surface declared via [`adele_core_set_mcp_surface`] hosts on the
 edge — and their status. The answer arrives as an `mcp_client_servers` view
 event carrying, per server: `name`, `transport` (`stdio`/`http`), `status`,
 `tool_count`, and `namespace` (or null).

 The sibling of [`adele_core_request_mcp_builtins`], and like it answerable with
 **no connection**: which external servers this surface hosts is a property of
 `client-mcp.toml`, so a settings panel can call this before the first connect.
 The server list is complete offline (each row reports `enabled` with a `0`
 tool count); the live tool counts and running/error status fill in once a
 connection has started the client MCP host. A surface that enables no external
 servers answers with an empty list — the honest "none configured".

 # Safety
 `core` must be a live handle from [`adele_core_new`].
 */
void adele_core_request_mcp_client_servers(Core *core);

/*
 Turn one built-in MCP server off (`disabled = true`) or back on for **this
 client's surface**, by writing `[surfaces.<surface>].disabled_builtins` in the
 shared `client-mcp.toml`.

 The write goes through the core because that file is machine-wide: every Adele
 client on the box reads the same one, and a second independent writer would be
 a correctness hazard for all of them. Only the declared surface's section is
 touched, so opting out here never disturbs another client's selection.

 Takes effect on the next [`adele_core_connect`] — a running MCP host is fixed
 at start. An `mcp_builtins` view event follows either way (including on
 failure, which also emits a `toast`), carrying the pending state so the panel
 stays honest in the meantime. A NULL or empty `name` is refused.

 # Safety
 `core` must be a live handle from [`adele_core_new`]; `name` must be NULL or a
 valid NUL-terminated UTF-8 string, borrowed for the call.
 */
void adele_core_set_mcp_builtin_disabled(Core *core, const char *name, bool disabled);

/*
 Send an arbitrary management command (an `api::Command` serialized as JSON)
 over the connector. The `CommandResult` is delivered later as a
 `command_result` view event carrying the same `request_id`, so the caller can
 correlate the reply. This is the generic settings/management channel
 (connections, purposes, knowledge base) beyond the typed chat intents.

 # Safety
 `core` must be a live handle; `request_id`/`command_json` must be null or
 valid C strings.
 */
void adele_core_send_command(Core *core, const char *request_id, const char *command_json);

/*
 Render untrusted markdown into a **sanitized HTML fragment**.

 This is what a host streams into an already-loaded page (via the page's
 update function — see [`adele_core_markdown_set_content_function`]) so a
 growing reply never reloads the document.

 Returns a caller-owned string to release with [`adele_core_string_free`];
 null input renders as the empty string. Never returns null.

 # Safety
 `text` must be null or point to a valid NUL-terminated C string that stays
 valid for the duration of the call.
 */
char *adele_core_render_markdown(const char *text);

/*
 Render untrusted markdown into a **complete, CSP-locked page** for a single
 message bubble: transparent background, system-appearance aware, no network,
 self-reporting height, and an in-place update hook.

 This is what a host loads once per message (with a null base URL); subsequent
 updates go through [`adele_core_render_markdown`] plus the page's update
 function, which keeps the pinned script hash — and therefore the page —
 unchanged.

 Returns a caller-owned string to release with [`adele_core_string_free`];
 null input renders an empty bubble. Never returns null.

 # Safety
 `text` must be null or point to a valid NUL-terminated C string that stays
 valid for the duration of the call.
 */
char *adele_core_render_markdown_document(const char *text);

/*
 Name of the script-message handler the bubble page posts its pixel height
 to. The host must register a handler under exactly this name; an embedded
 engine does not self-size inside a native stack view.

 Returns a `'static` pointer — do not free it.
 */
const char *adele_core_markdown_height_handler_name(void);

/*
 Name of the global function the host calls (through host-side script
 evaluation) to swap a new render into an already-loaded bubble page.

 Returns a `'static` pointer — do not free it.
 */
const char *adele_core_markdown_set_content_function(void);

/*
 Free a string returned by [`adele_core_render_markdown`] or
 [`adele_core_render_markdown_document`]. Null is a no-op.

 # Safety
 `text` must be null, or a pointer returned by one of those two functions and
 not yet freed. Do not pass the `'static` pointers from the bridge-name
 accessors.
 */
void adele_core_string_free(char *text);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ADELE_CLIENT_CORE_H */
